name: skymap
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5.3.4
  - matplotlib>=3.8
  - numpy>=1.26.0
  - pip>=23.3
  - python>=3.11
  - scipy>=1.11.4
  - healpy>=1.16.6
  - jupyterlab>=4.0.11
  - pandas>=2.1.4
